import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Bot, Database, Radar, Route, ShieldAlert, Clock3 } from "lucide-react";
import { dataService, type OrchestratorSnapshot } from "@/services/dataService";

const inputCards = [
  {
    icon: Database,
    title: "Pandal Registration Data",
    text: "Four CSV inputs: pandal, idol, procession, and vehicle records.",
    detail: "Static registration source for every procession and immersion decision.",
  },
  {
    icon: Radar,
    title: "Live Synthetic Feeds",
    text: "Crowd, traffic, ANPR, and weather signals generated by synthetic data scripts.",
    detail: "Used as if they were real-time feeds without introducing computer vision complexity.",
  },
  {
    icon: Bot,
    title: "Agent Mesh",
    text: "Pandal, ANPR, traffic, crowd, immersion, and resource agents work on different signals.",
    detail:
      "Each agent contributes a local view before the advisor merges them into one recommendation.",
  },
];

const outputCards = [
  {
    icon: Route,
    title: "Dynamic Allocation",
    text: "Route, slot, and crane assignment for each procession.",
  },
  {
    icon: ShieldAlert,
    title: "Proactive Crowd Prediction",
    text: "Forecast density near immersion points using upstream junction and traffic signals.",
  },
  {
    icon: Clock3,
    title: "Decision Support",
    text: "Delay, divert, permit, or restrict based on predicted load and queue pressure.",
  },
];

const safeText = (value: unknown, fallback: string) =>
  typeof value === "string" && value.trim() ? value : fallback;

export function AgenticApplicationOverview() {
  const [snapshot, setSnapshot] = useState<OrchestratorSnapshot | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;

    const loadSnapshot = async () => {
      try {
        const result = await dataService.getOrchestratorSnapshot();
        if (!active) return;
        setSnapshot(result);
        setError(null);
      } catch (loadError) {
        if (!active) return;
        setError(
          loadError instanceof Error ? loadError.message : "Failed to load live agent output",
        );
      } finally {
        if (active) setLoading(false);
      }
    };

    void loadSnapshot();
    const timer = window.setInterval(() => {
      void loadSnapshot();
    }, 15000);

    return () => {
      active = false;
      window.clearInterval(timer);
    };
  }, []);

  const liveDecision = snapshot?.decisions?.[0];
  const liveReports = snapshot?.agent_reports ?? [];

  return (
    <div className="flex-1 overflow-auto p-6 scrollbar-thin">
      <div className="max-w-6xl mx-auto space-y-6">
        <div className="glass rounded-2xl border border-[var(--panel-border)] p-6 relative overflow-hidden">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(0,180,255,0.16),transparent_35%),radial-gradient(circle_at_bottom_left,rgba(18,227,168,0.12),transparent_30%)]" />
          <div className="relative">
            <div className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">
              Application Overview
            </div>
            <h1 className="text-3xl font-semibold mt-1">Agentic AI Application</h1>
            <p className="text-muted-foreground max-w-3xl mt-2">
              Digital Twin for Event Operations. The platform combines registration data, synthetic
              live feeds, and specialized agents to predict crowd pressure, assign immersion
              resources, and recommend safer routes.
            </p>
            <div className="mt-4 flex flex-wrap gap-2 text-[11px] uppercase tracking-[0.14em] text-muted-foreground">
              <span className="chip">Python API: /api/orchestrator</span>
              <span className="chip">
                {loading
                  ? "Loading live agent output"
                  : error
                    ? "Live output unavailable"
                    : `Live snapshot ${snapshot?.generated_at ? "synced" : "ready"}`}
              </span>
            </div>
          </div>
        </div>

        <div className="grid gap-4 lg:grid-cols-[1.25fr_0.95fr]">
          <div className="space-y-4">
            {inputCards.map((card, index) => (
              <motion.div
                key={card.title}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.08 }}
                className="glass rounded-xl border border-[var(--panel-border)] p-4"
              >
                <div className="flex items-start gap-4">
                  <div className="w-11 h-11 rounded-lg bg-[var(--secondary)] grid place-items-center shrink-0">
                    <card.icon className="w-5 h-5 text-[var(--color-info)]" />
                  </div>
                  <div className="min-w-0">
                    <div className="text-sm font-semibold">{card.title}</div>
                    <p className="text-sm text-muted-foreground mt-1">{card.text}</p>
                    <p className="text-xs text-muted-foreground mt-2">{card.detail}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>

          <div className="space-y-4">
            <div className="glass rounded-xl border border-[var(--panel-border)] p-4">
              <div className="text-[11px] uppercase tracking-[0.16em] text-muted-foreground">
                Agentic Flow
              </div>
              <div className="mt-4 space-y-3">
                {[
                  "Pandal registration portal ingests CSV inputs.",
                  "Synthetic live feeds update ANPR, traffic, crowd, and weather state.",
                  "Local agents analyze their own signal domain.",
                  "The advisor merges outputs into allocation and risk recommendations.",
                ].map((item, index) => (
                  <div key={item} className="flex gap-3 items-start">
                    <div className="mt-1 w-6 h-6 rounded-full bg-[var(--accent)] grid place-items-center text-[11px] font-semibold text-foreground shrink-0">
                      {index + 1}
                    </div>
                    <p className="text-sm text-foreground/90 leading-relaxed">{item}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1 xl:grid-cols-3">
              {outputCards.map((card, index) => (
                <motion.div
                  key={card.title}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.18 + index * 0.08 }}
                  className="glass rounded-xl border border-[var(--panel-border)] p-4"
                >
                  <card.icon className="w-5 h-5 text-[var(--color-info)]" />
                  <div className="mt-3 text-sm font-semibold">{card.title}</div>
                  <p className="text-sm text-muted-foreground mt-1">{card.text}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        <div className="glass rounded-xl border border-[var(--panel-border)] p-5">
          <div className="text-[11px] uppercase tracking-[0.16em] text-muted-foreground">
            Recommended Outcome
          </div>
          <div className="mt-3 grid gap-3 md:grid-cols-3">
            {[
              "Assign the best available ghat and crane for each procession.",
              "Predict density near immersion locations from upstream junctions.",
              "Hold, divert, or permit entry based on computed risk.",
            ].map((item) => (
              <div
                key={item}
                className="rounded-lg border border-[var(--panel-border)] bg-background/30 p-3 text-sm leading-relaxed"
              >
                {item}
              </div>
            ))}
          </div>
        </div>

        <div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]">
          <div className="glass rounded-xl border border-[var(--panel-border)] p-5">
            <div className="text-[11px] uppercase tracking-[0.16em] text-muted-foreground">
              Live Orchestrator Snapshot
            </div>
            <div className="mt-3 space-y-3">
              {error ? (
                <div className="rounded-lg border border-[var(--panel-border)] bg-background/30 p-3 text-sm text-muted-foreground">
                  {error}
                </div>
              ) : liveDecision ? (
                <>
                  <div className="rounded-lg border border-[var(--panel-border)] bg-background/30 p-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <div>
                        <div className="text-sm font-semibold">
                          {safeText(liveDecision.pandal_id, "Unknown Pandal")}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          {safeText(liveDecision.vehicle_number, "No vehicle")}
                        </div>
                      </div>
                      <div className="chip">
                        {safeText(liveDecision.crowd_risk, "unknown")} risk
                      </div>
                    </div>
                    <div className="mt-3 grid gap-2 md:grid-cols-2 text-sm">
                      <div>
                        Route:{" "}
                        <span className="font-medium">{safeText(liveDecision.route, "TBD")}</span>
                      </div>
                      <div>
                        Ghat:{" "}
                        <span className="font-medium">{safeText(liveDecision.ghat, "TBD")}</span>
                      </div>
                      <div>
                        Crane: <span className="font-medium">{liveDecision.crane}</span>
                      </div>
                      <div>
                        Slot:{" "}
                        <span className="font-medium">
                          {safeText(liveDecision.slot_start, "TBD")}
                        </span>
                      </div>
                      <div>
                        Wait:{" "}
                        <span className="font-medium">{liveDecision.waiting_minutes} min</span>
                      </div>
                      <div>
                        Entry now:{" "}
                        <span className="font-medium">
                          {liveDecision.allow_entry_now ? "Allowed" : "Hold"}
                        </span>
                      </div>
                    </div>
                    <div className="mt-3 flex flex-wrap gap-2">
                      {liveDecision.actions.slice(0, 4).map((action) => (
                        <span
                          key={action}
                          className="rounded-full border border-[var(--panel-border)] bg-black/20 px-3 py-1 text-xs text-muted-foreground"
                        >
                          {action}
                        </span>
                      ))}
                    </div>
                  </div>
                  <div className="grid gap-3 sm:grid-cols-3">
                    {snapshot?.decisions.slice(0, 3).map((decision) => (
                      <div
                        key={`${decision.pandal_id}-${decision.vehicle_number}`}
                        className="rounded-lg border border-[var(--panel-border)] bg-background/30 p-3 text-sm"
                      >
                        <div className="font-semibold">{decision.pandal_id}</div>
                        <div className="text-xs text-muted-foreground">
                          {decision.route} · {decision.ghat}
                        </div>
                        <div className="mt-2 text-[11px] uppercase tracking-[0.14em] text-muted-foreground">
                          {decision.crowd_risk} risk
                        </div>
                      </div>
                    ))}
                  </div>
                </>
              ) : (
                <div className="rounded-lg border border-[var(--panel-border)] bg-background/30 p-3 text-sm text-muted-foreground">
                  Waiting for the first live orchestrator snapshot.
                </div>
              )}
            </div>
          </div>

          <div className="glass rounded-xl border border-[var(--panel-border)] p-5">
            <div className="text-[11px] uppercase tracking-[0.16em] text-muted-foreground">
              Agent Output Feed
            </div>
            <div className="mt-3 space-y-3">
              {liveReports.length ? (
                liveReports.slice(0, 6).map((report, index) => (
                  <div
                    key={`${report.agent_name}-${index}`}
                    className="rounded-lg border border-[var(--panel-border)] bg-background/30 p-3"
                  >
                    <div className="text-[11px] uppercase tracking-[0.14em] text-[var(--color-info)]">
                      {report.agent_name}
                    </div>
                    <div className="mt-1 text-sm text-foreground/90">{report.summary}</div>
                  </div>
                ))
              ) : (
                <div className="rounded-lg border border-[var(--panel-border)] bg-background/30 p-3 text-sm text-muted-foreground">
                  Live agent summaries will appear here once the Python API is available.
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
